<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\FeaturedBook;

class FeaturedBookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            ['judul'=>'Laut Bercerita','penulis'=>'Leila S. Chudori','penerbit'=>'KPG','tahun'=>2017,'isbn'=>'978-602-0799-00-2','jumlah_halaman'=>394,'bahasa'=>'Indonesia','kategori'=>'Fiksi','sinopsis'=>'Kisah aktivis mahasiswa yang menghilang di era Orde Baru.','genres'=>['Fiksi','Sejarah'],'cover_url'=>null,'gradient_from'=>'#C7E7FF','gradient_to'=>'#D4F6FF','rating_avg'=>4.5,'rating_count'=>120],
            ['judul'=>'Cantik Itu Luka','penulis'=>'Eka Kurniawan','penerbit'=>'Penerbit Buku Kompas','tahun'=>2002,'isbn'=>'978-979-709-123-4','jumlah_halaman'=>474,'bahasa'=>'Indonesia','kategori'=>'Fiksi','sinopsis'=>'Dewi Ayu bangkit dari kubur dan menyaksikan dunia penuh kekerasan dan kecantikan.','genres'=>['Fiksi'],'cover_url'=>null,'gradient_from'=>'#FFDDAF','gradient_to'=>'#C7E7FF','rating_avg'=>4.3,'rating_count'=>95],
            ['judul'=>'Ronggeng Dukuh Paruk','penulis'=>'Ahmad Tohari','penerbit'=>'Gramedia','tahun'=>1982,'isbn'=>'978-979-686-123-4','jumlah_halaman'=>422,'bahasa'=>'Indonesia','kategori'=>'Fiksi','sinopsis'=>'Srintil menjadi ronggeng yang dikagumi, terjebak pusaran tragedi politik.','genres'=>['Fiksi','Klasik'],'cover_url'=>null,'gradient_from'=>'#D4F6FF','gradient_to'=>'#FFDDAF','rating_avg'=>4.6,'rating_count'=>88],
            ['judul'=>'Pulang','penulis'=>'Tere Liye','penerbit'=>'Republika','tahun'=>2015,'isbn'=>'978-602-0851-00-7','jumlah_halaman'=>406,'bahasa'=>'Indonesia','kategori'=>'Fiksi','sinopsis'=>'Bujang mencari arti pulang di dunia bayangan penuh intrik.','genres'=>['Fiksi'],'cover_url'=>null,'gradient_from'=>'#FFDDAF','gradient_to'=>'#C7E7FF','rating_avg'=>4.6,'rating_count'=>200],
            ['judul'=>'Bumi','penulis'=>'Tere Liye','penerbit'=>'Gramedia','tahun'=>2014,'isbn'=>'978-602-0378-00-2','jumlah_halaman'=>358,'bahasa'=>'Indonesia','kategori'=>'Fantasi','sinopsis'=>'Raib, Ali, dan Seli berpetualang ke klan-klan misterius di dunia paralel.','genres'=>['Fantasi'],'cover_url'=>null, 'gradient_from'=>'#C7E7FF','gradient_to'=>'#D4F6FF','rating_avg'=>4.8,'rating_count'=>350],
            ['judul'=>'Hujan','penulis'=>'Tere Liye','penerbit'=>'Gramedia','tahun'=>2016,'isbn'=>'978-602-0378-01-9','jumlah_halaman'=>320,'bahasa'=>'Indonesia','kategori'=>'Fiksi','sinopsis'=>'Lail dan Esok tumbuh bersama di tengah bencana dan teknologi penghapus ingatan.','genres'=>['Fiksi','Romansa'],'cover_url'=>null,'gradient_from'=>'#D4F6FF','gradient_to'=>'#FFDDAF','rating_avg'=>4.4,'rating_count'=>180],
            ['judul'=>'Laskar Pelangi','penulis'=>'Andrea Hirata','penerbit'=>'Bentang Pustaka','tahun'=>2005,'isbn'=>'978-979-3062-79-3','jumlah_halaman'=>534,'bahasa'=>'Indonesia','kategori'=>'Fiksi','sinopsis'=>'Sepuluh anak dari Belitung berjuang meraih mimpi di tengah keterbatasan.','genres'=>['Fiksi','Inspirasi'],'cover_url'=>null,'gradient_from'=>'#FFDDAF','gradient_to'=>'#D4F6FF','rating_avg'=>4.7,'rating_count'=>500],
            ['judul'=>'Negeri 5 Menara','penulis'=>'A. Fuadi','penerbit'=>'Gramedia','tahun'=>2009,'isbn'=>'978-979-225-123-4','jumlah_halaman'=>422,'bahasa'=>'Indonesia','kategori'=>'Fiksi','sinopsis'=>'Enam sahabat di pesantren bermimpi mengunjungi menara dunia.','genres'=>['Fiksi','Inspirasi'],'cover_url'=>null,'gradient_from'=>'#D4F6FF','gradient_to'=>'#C7E7FF','rating_avg'=>4.3,'rating_count'=>210],
            ['judul'=>'Perahu Kertas','penulis'=>'Dee Lestari','penerbit'=>'Tiga Serangkai','tahun'=>2009,'isbn'=>'978-979-045-123-4','jumlah_halaman'=>444,'bahasa'=>'Indonesia','kategori'=>'Fiksi','sinopsis'=>'Kugy dan Keenan mengejar mimpi sambil tersesat dalam cinta.','genres'=>['Fiksi','Romansa'],'cover_url'=>null,'gradient_from'=>'#C7E7FF','gradient_to'=>'#FFDDAF','rating_avg'=>4.2,'rating_count'=>160],
            ['judul'=>'Supernova: Ksatria, Puteri, dan Bintang Jatuh','penulis'=>'Dee Lestari','penerbit'=>'Bentang Pustaka','tahun'=>2001,'isbn'=>'978-979-3062-45-8','jumlah_halaman'=>404,'bahasa'=>'Indonesia','kategori'=>'Fiksi','sinopsis'=>'Dua sahabat menulis novel yang mengubah kehidupan orang-orang di sekitarnya.','genres'=>['Fiksi'],'cover_url'=>null,'gradient_from'=>'#C7E7FF','gradient_to'=>'#FFDDAF','rating_avg'=>4.4,'rating_count'=>140],
            ['judul'=>'Sapiens','penulis'=>'Yuval Noah Harari','penerbit'=>'KPG','tahun'=>2011,'isbn'=>'978-602-6637-00-4','jumlah_halaman'=>512,'bahasa'=>'Indonesia','kategori'=>'Non-Fiksi','sinopsis'=>'Sejarah umat manusia dari zaman batu hingga revolusi sains.','genres'=>['Non-Fiksi','Sejarah'],'cover_url'=>null,'gradient_from'=>'#D4F6FF','gradient_to'=>'#C7E7FF','rating_avg'=>4.6,'rating_count'=>300],
            ['judul'=>'Atomic Habits','penulis'=>'James Clear','penerbit'=>'Gramedia','tahun'=>2018,'isbn'=>'978-602-0636-00-1','jumlah_halaman'=>320,'bahasa'=>'Indonesia','kategori'=>'Non-Fiksi','sinopsis'=>'Panduan membangun kebiasaan baik lewat perubahan kecil yang konsisten.','genres'=>['Non-Fiksi','Pengembangan Diri'],'cover_url'=>null,'gradient_from'=>'#FFDDAF','gradient_to'=>'#D4F6FF','rating_avg'=>4.8,'rating_count'=>450],
            ['judul'=>'Filosofi Teras','penulis'=>'Henry Manampiring','penerbit'=>'Penerbit Buku Kompas','tahun'=>2018,'isbn'=>'978-602-412-345-6','jumlah_halaman'=>280,'bahasa'=>'Indonesia','kategori'=>'Non-Fiksi','sinopsis'=>'Filsafat Stoa untuk menghadapi kecemasan hidup modern.','genres'=>['Non-Fiksi','Filosofi'],'cover_url'=>null,'gradient_from'=>'#C7E7FF','gradient_to'=>'#FFDDAF','rating_avg'=>4.5,'rating_count'=>250],
            ['judul'=>'Di Tanah Lada','penulis'=>'Ziggy Zezsyazeoviennazabrizkie','penerbit'=>'Gramedia','tahun'=>2023,'isbn'=>'978-602-0651-00-4','jumlah_halaman'=>240,'bahasa'=>'Indonesia','kategori'=>'Fiksi','sinopsis'=>'Kekerasan domestik melalui perspektif anak-anak yang polos namun cerdas.','genres'=>['Fiksi'],'cover_url'=>null,'gradient_from'=>'#D4F6FF','gradient_to'=>'#FFDDAF','rating_avg'=>4.1,'rating_count'=>50],
            ['judul'=>'Project Hail Mary','penulis'=>'Andy Weir','penerbit'=>'Gramedia','tahun'=>2021,'isbn'=>'978-623-0400-12-3','jumlah_halaman'=>480,'bahasa'=>'Indonesia','kategori'=>'Fiksi','sinopsis'=>'Seorang astronot terbangun di pesawat luar angkasa tanpa ingatan.','genres'=>['Fiksi','Sci-Fi'],'cover_url'=>null,'gradient_from'=>'#C7E7FF','gradient_to'=>'#D4F6FF','rating_avg'=>4.7,'rating_count'=>280],
            ['judul'=>'The Psychology of Money','penulis'=>'Morgan Housel','penerbit'=>'Gramedia','tahun'=>2020,'isbn'=>'978-602-0640-00-8','jumlah_halaman'=>256,'bahasa'=>'Indonesia','kategori'=>'Non-Fiksi','sinopsis'=>'Pelajaran abadi tentang kekayaan, keserakahan, dan kebahagiaan.','genres'=>['Non-Fiksi','Bisnis'],'cover_url'=>null,'gradient_from'=>'#FFDDAF','gradient_to'=>'#C7E7FF','rating_avg'=>4.6,'rating_count'=>320],
            ['judul'=>'Dunia Sophie','penulis'=>'Jostein Gaarder','penerbit'=>'Mizan','tahun'=>1991,'isbn'=>'978-979-433-123-4','jumlah_halaman'=>560,'bahasa'=>'Indonesia','kategori'=>'Fiksi','sinopsis'=>'Perjalanan seorang gadis mempelajari filsafat dari zaman kuno hingga modern.','genres'=>['Fiksi','Filosofi'],'cover_url'=>null,'gradient_from'=>'#D4F6FF','gradient_to'=>'#C7E7FF','rating_avg'=>4.3,'rating_count'=>190],
            ['judul'=>'Keajaiban Toko Kelontong Namiya','penulis'=>'Keigo Higashino','penerbit'=>'Gramedia','tahun'=>2012,'isbn'=>'978-602-0378-02-6','jumlah_halaman'=>376,'bahasa'=>'Indonesia','kategori'=>'Fiksi','sinopsis'=>'Toko kelontong tua yang menjadi tempat curhat dan mengubah hidup banyak orang.','genres'=>['Fiksi'],'cover_url'=>null,'gradient_from'=>'#FFDDAF','gradient_to'=>'#C7E7FF','rating_avg'=>4.5,'rating_count'=>210],
            ['judul'=>'Hidup Ini Terlalu Banyak Kamu','penulis'=>'Pidi Baiq','penerbit'=>'Pastel Books','tahun'=>2025,'isbn'=>'978-623-0900-12-5','jumlah_halaman'=>280,'bahasa'=>'Indonesia','kategori'=>'Fiksi','sinopsis'=>'Buku reflektif dengan gaya bahasa sederhana yang menyentuh hati.','genres'=>['Fiksi'],'cover_url'=>null,'gradient_from'=>'#C7E7FF','gradient_to'=>'#FFDDAF','rating_avg'=>0,'rating_count'=>0],
            ['judul'=>'The Let Them Theory','penulis'=>'Mel Robbins','penerbit'=>'Gramedia','tahun'=>2024,'isbn'=>'978-623-0400-13-0','jumlah_halaman'=>320,'bahasa'=>'Indonesia','kategori'=>'Non-Fiksi','sinopsis'=>'Solusi untuk burnout akibat tekanan sosial.','genres'=>['Non-Fiksi','Pengembangan Diri'],'cover_url'=>null,'gradient_from'=>'#D4F6FF','gradient_to'=>'#FFDDAF','rating_avg'=>4.2,'rating_count'=>80],
        ];

        foreach ($books as $b) {
            FeaturedBook::create($b);
        }
    }
}
